version: '2.4'

x-env: &env
  TENSORBOARD_PORT: &TENSORBOARD_PORT ${TENSORBOARD_PORT:?}
  NVIDIA_VISIBLE_DEVICES:  &NVIDIA_VISIBLE_DEVICES ${NVIDIA_VISIBLE_DEVICES:-all}


x-app: &app
  shm_size: '30gb'
  runtime: nvidia
  build:
    context: .
  volumes:
    - .:/app


services:
  app:
    <<: *app
    environment:
      NVIDIA_VISIBLE_DEVICES: *NVIDIA_VISIBLE_DEVICES

  tensorboard:
    <<: *app
    command: tensorboard --logdir=. --host=0.0.0.0 --port=${TENSORBOARD_PORT}
    ports:
      - "${TENSORBOARD_PORT}:${TENSORBOARD_PORT}"
