name: v2-fine
seed: 1024
fold: 1
kfold: 5
batch_size: 16
model_name: tf_efficientnet_b4_ns
lr: 0.00010564766155184
image_size: 512
embedding_size: 1536
arcface_scale: 22.518394947621836
arcface_margin: 4.949062094859887
brightness_limit: 0.291
contrast_limit: 0.291
hue_shift_limit: 0.28
sat_shift_limit: 0.225
val_shift_limit: 0.28
scale_limit: 0.18529016025844874
sub_centers: 4
rotate_limit: 32.394467397006466
warmup_t: 1
epochs: 57
use_scheduler: false
patience: 11
num_model_nos: 244
n_neighbors: 200
vflip_p: 0.0
hflip_p: 0.0
train_with_flipped: true
loss_type: "ArcFaceLoss"
registry_rot_augmentations:
  - 90
  - 180
  - 270

previous:
  name: v2
